### ISSUE TITLE
TimeoutException after Captcha

### ISSUE THREAD

**Issue by richmarv** [flathunters/flathunter#113]
Hi!
I experience timeouts right after the captcha solving, but it is not a steady problem, i.e. when I restart the script it runs thorugh. My 2_captcha setup is working (most of the time as you see).

Here is a typical log:
```
[2021/03/16 15:50:07|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2021/03/16 15:50:12|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2021/03/16 15:50:12|abstract_crawler.py|DEBUG   ]: Captcha promise: OK|03AGdBq24s86a4LSPuU8CJCT1gF-JzbFcRDkyXAtQwSgzP6QK9Yv9z3iA0mlzfBdIh5hv0H1t7s-PJnBDD0yFgaXJVaYr1dba57vCu_66yXiQ6gzeRtIcQwJYKgctw9_8Y9d7ThbShmLlG7v6Y5qWTmELSyX0QiDNInqIDNwM5DXCNmzLTw1lrVoENlgXoKerJbJhO0Gy1aZdO6-gV-nD_wqPpGI5NDKGnKcMXdajE4L6FxJILEnyXY77HAnI05MRbbI-dLIFEUAKKenWovdyMLgjDIbb83dZhoEB8iFyEDmDhV07Zea2CS7MEvLAXT9B-0s9D3mmR0pfZbhQ9bF_KEh43k83kxBLZ1_jjhebf2lECm6LfWKKv1MCPSsObwNsrhtt2ivCxKJqRaoqjXlDHxkRyyRh0p6oyvjiX8tlx0Iynse7oX2w2FvEqX9htv4F_M06EPkweyoXGx3-rEHPyA3IqhTCQXbow6ChGvaF1Y9S4Ze1AwHuveto
Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "flathunt.py", line 50, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/m/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/m/flathunter/flathunter/hunter.py", line 22, in crawl_for_exposes
    for searcher in self.config.searchers()
  File "/home/m/flathunter/flathunter/hunter.py", line 23, in <listcomp>
    for url in self.config.get('urls', list())])
  File "/home/m/flathunter/flathunter/abstract_crawler.py", line 136, in crawl
    return self.get_results(url, max_pages)
  File "/home/m/flathunter/flathunter/crawl_immobilienscout.py", line 60, in get_results
    soup = self.get_page(search_url, self.driver, page_no)
  File "/home/m/flathunter/flathunter/crawl_immobilienscout.py", line 120, in get_page
    return self.get_soup_from_url(search_url.format(page_no), driver=driver, captcha_api_key=self.captcha_api_key, checkbox=self.checkbox, afterlogin_string=self.afterlogin_string)
  File "/home/m/flathunter/flathunter/abstract_crawler.py", line 75, in get_soup_from_url
    self.resolvecaptcha(driver, checkbox, afterlogin_string, captcha_api_key)
  File "/home/m/flathunter/flathunter/abstract_crawler.py", line 153, in resolvecaptcha
    self._solve(driver, api_key)
  File "/home/m/flathunter/flathunter/abstract_crawler.py", line 181, in _solve
    self._check_if_iframe_not_visible(driver)
  File "/home/m/flathunter/flathunter/abstract_crawler.py", line 216, in _check_if_iframe_not_visible
    (By.CSS_SELECTOR, "iframe[src^='https://www.google.com/recaptcha/api2/anchor?']")))
  File "/home/m/.pyenv/versions/venv_flathunter/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

here are two examples with more context:

[timeout_1.log](https://github.com/flathunters/flathunter/files/6155224/timeout_1.log)
[timeout_2.log](https://github.com/flathunters/flathunter/files/6155225/timeout_2.log)

I am just guessing here: maybe after 2 min of no answer the script raises the timeoutException?

Thanks for looking into it!
Marvin

**Comment by choeffer** [comment]
I encounter the same error randomly in conjunction with 2captcha.

```shell
Traceback (most recent call last):
  File "/home/choeffer/Dokumente/flathunter/flathunt.py", line 89, in <module>
    main()
  File "/home/choeffer/Dokumente/flathunter/flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "/home/choeffer/Dokumente/flathunter/flathunt.py", line 50, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 21, in crawl_for_exposes
    return chain(*[searcher.crawl(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 21, in <listcomp>
    return chain(*[searcher.crawl(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/abstract_crawler.py", line 136, in crawl
    return self.get_results(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/crawl_immobilienscout.py", line 60, in get_results
    soup = self.get_page(search_url, self.driver, page_no)
  File "/home/choeffer/Dokumente/flathunter/flathunter/crawl_immobilienscout.py", line 120, in get_page
    return self.get_soup_from_url(search_url.format(page_no), driver=driver, captcha_api_key=self.captcha_api_key, checkbox=self.checkbox, afterlogin_string=self.afterlogin_string)
  File "/home/choeffer/Dokumente/flathunter/flathunter/abstract_crawler.py", line 73, in get_soup_from_url
    driver.get(url)
  File "/home/choeffer/Dokumente/flathunter/venv/lib64/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/choeffer/Dokumente/flathunter/venv/lib64/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/choeffer/Dokumente/flathunter/venv/lib64/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299,797
  (Session info: headless chrome=89.0.4389.90)
```

If you need any further information, please let me know.

**Comment by iwasherefirst2** [comment]
I have the same issue..

```
[2022/01/25 07:00:13|config.py         |INFO    ]: Using config /home/adam/flathunter/config.yaml
Traceback (most recent call last):
  File "/home/adam/flathunter/flathunt.py", line 95, in <module>
    main()
  File "/home/adam/flathunter/flathunt.py", line 92, in main
    launch_flat_hunt(config)
  File "/home/adam/flathunter/flathunt.py", line 47, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/adam/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/adam/flathunter/flathunter/hunter.py", line 22, in crawl_for_exposes
    for searcher in self.config.searchers()
  File "/home/adam/flathunter/flathunter/hunter.py", line 23, in <listcomp>
    for url in self.config.get('urls', list())])
  File "/home/adam/flathunter/flathunter/abstract_crawler.py", line 142, in crawl
    return self.get_results(url, max_pages)
  File "/home/adam/flathunter/flathunter/crawl_immobilienscout.py", line 60, in get_results
    soup = self.get_page(search_url, self.driver, page_no)
  File "/home/adam/flathunter/flathunter/crawl_immobilienscout.py", line 120, in get_page
    return self.get_soup_from_url(search_url.format(page_no), driver=driver, captcha_api_key=self.captcha_api_key, checkbox=self.checkbox, afterlogin_string=self.afterlogin_string)
  File "/home/adam/flathunter/flathunter/abstract_crawler.py", line 82, in get_soup_from_url
    return BeautifulSoup(driver.page_source, 'html.parser')
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=97.0.4692.71)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-166-generic x86_64)

```

Any idea how to fix it?

**Comment by iwasherefirst2** [comment]
Turned out that this happened because to many browser instances were open, every time the script is started, it will open up a new chrome instance. Calling `pkill chrome` fixed it for me.

**Comment by alexanderroidl** [comment]
@richmarv Did you manage to solve your problem? Please let me know, so I can close the issue. 😊
