### ISSUE TITLE
selenium.common.exceptions.TimeoutException: Message: timeout

### ISSUE THREAD

**Issue by iwasherefirst2** [flathunters/flathunter#145]
The script was working fine for a week, now I always get this exception:
```

[2022/01/25 07:00:13|config.py         |INFO    ]: Using config /home/adam/flathunter/config.yaml
Traceback (most recent call last):
  File "/home/adam/flathunter/flathunt.py", line 95, in <module>
    main()
  File "/home/adam/flathunter/flathunt.py", line 92, in main
    launch_flat_hunt(config)
  File "/home/adam/flathunter/flathunt.py", line 47, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/adam/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/adam/flathunter/flathunter/hunter.py", line 22, in crawl_for_exposes
    for searcher in self.config.searchers()
  File "/home/adam/flathunter/flathunter/hunter.py", line 23, in <listcomp>
    for url in self.config.get('urls', list())])
  File "/home/adam/flathunter/flathunter/abstract_crawler.py", line 142, in crawl
    return self.get_results(url, max_pages)
  File "/home/adam/flathunter/flathunter/crawl_immobilienscout.py", line 60, in get_results
    soup = self.get_page(search_url, self.driver, page_no)
  File "/home/adam/flathunter/flathunter/crawl_immobilienscout.py", line 120, in get_page
    return self.get_soup_from_url(search_url.format(page_no), driver=driver, captcha_api_key=self.captcha_api_key, checkbox=self.checkbox, afterlogin_string=self.afterlogin_string)
  File "/home/adam/flathunter/flathunter/abstract_crawler.py", line 82, in get_soup_from_url
    return BeautifulSoup(driver.page_source, 'html.parser')
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=97.0.4692.71)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-166-generic x86_64)


```

Any idea what could cause this?

**Comment by iwasherefirst2** [comment]
okay just noticed that this is a duplicate of https://github.com/flathunters/flathunter/issues/113

**Comment by iwasherefirst2** [comment]
Added debug and noticed that although this is a TimeoutException, it is triggered by another reason, I enabled debug and I still get issus thrown:
```

[2022/02/13 07:22:40|crawl_immobilienscout.py|DEBUG   ]: Got search URL https://www.immobilienscout24.de/Suche/shape/wohnung-mieten?shape=ZWhgX0l3e3NvQWZ9QXVhQmR7QG95Q2FjQXVfTntsQnd9Q3F4QF92R2tkQ3tpQF9yQm17QmttQW9Ud3lCYHtAbWtAdGNBY3VBantNZURkcVBsZUF_ZUJgYUxpYUB0ckFoYUBqYEF4dEE.&haspromotion=false&numberofrooms=3.5-&price=0.0-1600.0&livingspace=90.0-&exclusioncriteria=swapflat&pricetype=rentpermonth&sorting=2&pagenumber={0}
Traceback (most recent call last):
  File "/home/adam/flathunter/flathunt.py", line 95, in <module>
    main()
  File "/home/adam/flathunter/flathunt.py", line 92, in main
    launch_flat_hunt(config)
  File "/home/adam/flathunter/flathunt.py", line 51, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/adam/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/adam/flathunter/flathunter/hunter.py", line 22, in crawl_for_exposes
    for searcher in self.config.searchers()
  File "/home/adam/flathunter/flathunter/hunter.py", line 23, in <listcomp>
    for url in self.config.get('urls', list())])
  File "/home/adam/flathunter/flathunter/abstract_crawler.py", line 142, in crawl
    return self.get_results(url, max_pages)
  File "/home/adam/flathunter/flathunter/crawl_immobilienscout.py", line 60, in get_results
    soup = self.get_page(search_url, self.driver, page_no)
  File "/home/adam/flathunter/flathunter/crawl_immobilienscout.py", line 120, in get_page
    return self.get_soup_from_url(search_url.format(page_no), driver=driver, captcha_api_key=self.captcha_api_key, checkbox=self.checkbox, afterlogin_string=self.afterlogin_string)
  File "/home/adam/flathunter/flathunter/abstract_crawler.py", line 77, in get_soup_from_url
    driver.get(url)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 292,475
  (Session info: headless chrome=98.0.4758.80)

```

Can anyone help me? I reinstalled my server and it worked well for one week, now its going back to this issue. I crawl websites ever 10min (600s)

**Comment by iwasherefirst2** [comment]
On each start a new chrome proccess will start. Killing those with `pkill chrome` fixed this problem.
