### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException

### ISSUE THREAD

**Issue by iwasherefirst2** [flathunters/flathunter#148]
I have installed this onto a Ubuntu 18.04.6 LTS Server. I installed chrome and downloaded the appropriate chrome-driver, in my case v98

Now, whenever I run hunter.py I receive `selenium.common.exceptions.SessionNotCreatedException` 

```Traceback (most recent call last):
  File "/home/adam/flathunter/flathunt.py", line 95, in <module>
    main()
  File "/home/adam/flathunter/flathunt.py", line 68, in main
    config = Config(config_handle.name)
  File "/home/adam/flathunter/flathunter/config.py", line 29, in __init__
    self.__searchers__ = [CrawlImmobilienscout(self),
  File "/home/adam/flathunter/flathunter/crawl_immobilienscout.py", line 43, in __init__
    self.driver = self.configure_driver(self.driver_executable_path, self.driver_arguments)
  File "/home/adam/flathunter/flathunter/abstract_crawler.py", line 53, in configure_driver
    driver = webdriver.Chrome(executable_path=driver_path, options=chrome_options)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adam/.local/share/virtualenvs/flathunter-SBM5Nxub/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from tab crashed
  (Session info: headless chrome=98.0.4758.80)
```

Any idea what is causing this?

**Comment by iwasherefirst2** [comment]
Fixed by reinstall https://stackoverflow.com/questions/70984378/selenium-common-exceptions-sessionnotcreatedexception

**Comment by iwasherefirst2** [comment]
After reinstall, the error reoccurred after a while. I then found out that this error means that chromedriver could not be started. When I tried to start it manually, it failed with "port already open". I then added a "kill all chromdriver" to my shell script, and everything was working for a while. But now, the error is happening again, although I can start it manually..

**Comment by iwasherefirst2** [comment]
On each start a new chrome proccess will start. Killing those with `pkill chrome` fixed this problem.
