### ISSUE TITLE
Gettting Index Error occured for immoscout24

### ISSUE THREAD

**Issue by sc1ssors** [flathunters/flathunter#173]
After having configured everything in the `config.yaml` for scraping immobilienscout24.de, I am getting the following error: <br />
```
[2022/05/26 00:32:10|config.py         |INFO    ]: Using config /data/flathunter/config.yaml
[2022/05/26 00:32:11|flathunt.py       |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7fc98e320710>
[2022/05/26 00:32:11|crawl_immobilienscout.py|DEBUG   ]: Got search URL https://www.immobilienscout24.de/Suche/radius/wohnung-mieten?centerofsearchaddress=K%C3%B6ln;;;1276010028;Nordrhein-Westfalen;&numberofrooms=2.0-&price=-700.0&livingspace=40.0-&pricetype=rentpermonth&geocoordinates=50.95797;6.96838;2.0&enteredFrom=one_step_search&pagenumber={0}
[2022/05/26 00:32:11|crawl_immobilienscout.py|DEBUG   ]: Index Error occurred
[2022/05/26 00:32:11|crawl_immobilienscout.py|DEBUG   ]: []
[2022/05/26 00:32:11|crawl_immobilienscout.py|DEBUG   ]: extracted: 0
```
Here is my `config.yaml`:

```
---
verbose: true

loop:
    active: yes
    sleeping_time: 600

urls:
        - https://www.immobilienscout24.de/Suche/radius/wohnung-mieten?centerofsearchaddress=K%C3%B6ln;;;1276010028;Nordrhein-Westfalen;&numberofrooms=2.0-&price=-700.0&livingspace=40.0-&pricetype=rentpermonth&geocoordinates=50.95797;6.96838;2.0&enteredFrom=one_step_search
          

filters:

blacklist:

durations:
    - name: (redacted) 
      destination: (redacted)
      modes: 
          - gm_id: transit
            title: "Öff."
          - gm_id: bicycling
            title: "Rad"
    - name: (redacted)
      destination: (redacted)
      modes: 
          - gm_id: transit
            title: "Öff."
          - gm_id: driving
            title: "Auto"

message: |
    {title}
    Zimmer: {rooms}
    Größe: {size}
    Preis: {price}
    Ort: {address}

    {url}

google_maps_api:
    key: YOUR_API_KEY
    url: https://maps.googleapis.com/maps/api/distancematrix/json?origins={origin}&destinations={dest}&mode={mode}&sensor=true&key={key}&arrival_time={arrival}
    enable: False

2captcha:
        api_key: (redacted)
driver_path: /home/(redacted)/chromedriver
driver_arguments:
        - "--headless"
notifiers:
    - telegram

telegram:
   bot_token: (redacted)
   receiver_ids:
        - (redacted)

```
The script is working fine for crawling ebay-kleinanzeigen but I can't get immoscout24 to work.

**Comment by mordax7** [comment]
Do you use either twocaptcha or imagetypers?

**Comment by sc1ssors** [comment]
Tried it with both actually. Now I have enough credits for the rest of my captcha-solving life. But sadly, I get the same error, no matter which service I configure.

**Comment by mordax7** [comment]
I think somehow the Flathunter does not detect your driver. Could it be that your config is a bit broken.
Can you make sure that the 2captcha looks exactly like this(including whitespaces):
```
captcha:
     2captcha:
           api_key: (yourkey)
     driver_path: (chromedriverpath)
     driver_arguments:
       - "--headless"
```

**Comment by sc1ssors** [comment]
Thanks a lot, I actually oversaw that
```
#captcha
```
had to be commented out too. Now, the search is starting just fine. Unfortunately, another issues arises after the captcha was solved:
```
[2022/05/28 11:15:09|config.py         |INFO    ]: Using config /data/flathunter/config.yaml
[2022/05/28 11:15:10|flathunt.py       |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7f042a45b6d8>
[2022/05/28 11:15:10|crawl_immobilienscout.py|DEBUG   ]: Got search URL https://www.immobilienscout24.de/Suche/de/nordrhein-westfalen/bielefeld/erdgeschosswohnung-mieten?petsallowedtypes=yes%2Cnegotiable&numberofrooms=3.0-&exclusioncriteria=projectlisting%2Cswapflat&sorting=2&pagenumber={0}
[2022/05/28 11:15:12|twocaptcha_solver.py|INFO    ]: Trying to solve geetest.
[2022/05/28 11:15:12|twocaptcha_solver.py|DEBUG   ]: Got response from 2captcha/in: OK|70549027908
[2022/05/28 11:15:12|twocaptcha_solver.py|DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/05/28 11:15:12|twocaptcha_solver.py|INFO    ]: Captcha is not ready yet, waiting...
...
[2022/05/28 11:16:03|twocaptcha_solver.py|DEBUG   ]: Got response from 2captcha/res: OK|{"geetest_challenge":"be0ca69482d5e84d7e0042df817384fd","geetest_validate":"6b90617faf62e82da30e7cf6adb879cd","geetest_seccode":"6b90617faf62e82da30e7cf6adb879cd|jordan"}
[2022/05/28 11:16:06|hunter.py         |INFO    ]: Error while scraping url https://www.immobilienscout24.de/Suche/de/nordrhein-westfalen/bielefeld/erdgeschosswohnung-mieten?petsallowedtypes=yes%2Cnegotiable&numberofrooms=3.0-&exclusioncriteria=projectlisting%2Cswapflat&sorting=2:
Traceback (most recent call last):
  File "/data/flathunter/flathunter/hunter.py", line 25, in try_crawl
    return searcher.crawl(url, max_pages)
  File "/data/flathunter/flathunter/abstract_crawler.py", line 147, in crawl
    return self.get_results(url, max_pages)
  File "/data/flathunter/flathunter/crawl_immobilienscout.py", line 59, in get_results
    soup = self.get_page(search_url, self.driver, page_no)
  File "/data/flathunter/flathunter/crawl_immobilienscout.py", line 119, in get_page
    return self.get_soup_from_url(search_url.format(page_no), driver=driver, checkbox=self.checkbox, afterlogin_string=self.afterlogin_string)
  File "/data/flathunter/flathunter/abstract_crawler.py", line 87, in get_soup_from_url
    return BeautifulSoup(driver.page_source, 'html.parser')
  File "/home/sc1ssors/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/home/sc1ssors/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/sc1ssors/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
```
What could be the issue here?

**Comment by mordax7** [comment]
Make sure to pull the latest code stand, there was a bug in previous version

**Comment by sc1ssors** [comment]
Working great now, thank you very much!
