### ISSUE TITLE
Chrome Webdriver error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by Leolele99** [flathunters/flathunter#195]
Im trying to crawl Immobilienscout and have it all setup on the nwest version, but constantly run into this error:

[2022/08/06 10:35:58|<WebDriverManager>      |DEBUG   ]: ====== WebDriver manager ======
[2022/08/06 10:35:58|<WebDriverManager>      |DEBUG   ]: Get LATEST chromedriver version for google-chrome 104.0.5112
[2022/08/06 10:35:58|<WebDriverManager>      |DEBUG   ]: Driver [/home/flathunter/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
Traceback (most recent call last):
  File "flathunt.py", line 105, in <module>
    main()
  File "flathunt.py", line 76, in main
    config.init_searchers()
  File "/opt/flathunter/flathunter/config.py", line 44, in init_searchers
    CrawlImmobilienscout(self),
  File "/opt/flathunter/flathunter/crawl_immobilienscout.py", line 38, in __init__
    self.driver = self.configure_driver(driver_arguments)
  File "/opt/flathunter/flathunter/abstract_crawler.py", line 62, in configure_driver
    options=chrome_options
  File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 72, in __init__
    service_log_path, service, keep_alive)
  File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 97, in __init__
    options=options)
  File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:

My driver arguments so far are:
 driver_arguments:
          - "--headless"
          - "--disable-dev-shm-usage"
          - "--no-sandbox"
          - "--disable-extensions"

**Comment by Leolele99** [comment]
To add on, I reinstalled google-chrome-stable already, run on Debian10, and did NOT use root to run the bot.

**Comment by alexanderroidl** [comment]
Hi Leolele99. 👋 Please provide context to the following questions:

- Are you running a 64-bit-based Debian?
- Does Google Chrome start normally by itself?
- Is Flathunter working as expected when not crawling ImmoScout24?

Thank you! 😊

**Comment by Leolele99** [comment]
Hi,

- Yes it is 64-bit Debian 10.
- Kind of? As its a server without any Desktop environment I can only start it in headless mode which seems to work without error.
- Yes, everything else works fine and is in fact working without problem for days now.

Thansk for taking a look at this.

**Comment by abuchmueller** [comment]
I have the same issue when running Docker (macOS Intel).

**Comment by alexanderroidl** [comment]
@Leolele99 and @abuchmueller, could you try out my solution suggested in [this issue](https://github.com/flathunters/flathunter/issues/199) and tell me whether it worked? Thank you!

**Comment by codders** [comment]
@Leolele99 @abuchmueller did you have any additional feedback here? Otherwise I would close this.

**Comment by abuchmueller** [comment]
> feedback

I think this is fixed, docker runs stable for quite some time now with the right driver args.
