### ISSUE TITLE
gcloud app failing

### ISSUE THREAD

**Issue by abuchmueller** [flathunters/flathunter#198]
Hi, 

I can't get it to run in gCloud.
Cloud Build and Firestore API (native) are enabled.
Also can't browse the web interface of the app, if get 502 Errors (bad gateway).

I get the following from the logs:

```
2022-08-20 14:02:37 default[20220820t153924]  [2022-08-20 14:02:37 +0000] [23] [INFO] Worker exiting (pid: 23)
2022-08-20 14:02:37 default[20220820t153924]  Traceback (most recent call last):    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 202, in run      self.manage_workers()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 551, in manage_workers      self.spawn_workers()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 623, in spawn_workers      time.sleep(0.1 * random.random())    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld      self.reap_workers()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers      raise HaltServer(reason, self.WORKER_BOOT_ERROR)  gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-08-20 14:02:37 default[20220820t153924]
2022-08-20 14:02:37 default[20220820t153924]  During handling of the above exception, another exception occurred:
2022-08-20 14:02:37 default[20220820t153924]
2022-08-20 14:02:37 default[20220820t153924]  Traceback (most recent call last):    File "/layers/google.python.pip/pip/bin/gunicorn", line 8, in <module>      sys.exit(run())    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 67, in run      WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/base.py", line 231, in run      super().run()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run      Arbiter(self).run()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run      self.halt(reason=inst.reason, exit_status=inst.exit_status)    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt      self.stop()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop      time.sleep(0.1)    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld      self.reap_workers()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers      raise HaltServer(reason, self.WORKER_BOOT_ERROR)  gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-08-20 14:03:00 default[20220820t153924]  "GET / HTTP/1.1" 502
2022-08-20 14:03:00 default[20220820t153924]  [2022-08-20 14:03:00 +0000] [11] [INFO] Starting gunicorn 20.1.0
2022-08-20 14:03:00 default[20220820t153924]  [2022-08-20 14:03:00 +0000] [11] [INFO] Listening at: http://0.0.0.0:8081 (11)
2022-08-20 14:03:00 default[20220820t153924]  [2022-08-20 14:03:00 +0000] [11] [INFO] Using worker: gthread
2022-08-20 14:03:00 default[20220820t153924]  [2022-08-20 14:03:00 +0000] [20] [INFO] Booting worker with pid: 20
2022-08-20 14:03:00 default[20220820t153924]  [2022-08-20 14:03:00 +0000] [20] [ERROR] Exception in worker process
2022-08-20 14:03:00 default[20220820t153924]  Traceback (most recent call last):    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker      worker.init_process()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process      super().init_process()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process      self.load_wsgi()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi      self.wsgi = self.app.wsgi()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi      self.callable = self.load()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load      return self.load_wsgiapp()    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp      return util.import_app(self.app_uri)    File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app      mod = importlib.import_module(module)    File "/opt/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module      return _bootstrap._gcd_import(name[level:], package, level)    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import    File "<frozen importlib._bootstrap>", line 983, in _find_and_load    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked    File "<frozen importlib._bootstrap_external>", line 728, in exec_module    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed    File "/srv/main.py", line 3, in <module>      from flathunter.googlecloud_idmaintainer import GoogleCloudIdMaintainer    File "/srv/flathunter/googlecloud_idmaintainer.py", line 3, in <module>      import pytz  ModuleNotFoundError: No module named 'pytz'
2022-08-20 14:03:00 default[20220820t153924]  [2022-08-20 14:03:00 +0000] [20] [INFO] Worker exiting (pid: 20)
2022-08-20 14:03:00 default[20220820t153924]  [2022-08-20 14:03:00 +0000] [11] [INFO] Shutting down: Master
2022-08-20 14:03:00 default[20220820t153924]  [2022-08-20 14:03:00 +0000] [11] [INFO] Reason: Worker failed to boot.
```

**Comment by abuchmueller** [comment]
The solution was to generate the missing requirements.txt by running `pip freeze > requirements.txt` in the flathunter directory, then redeploy to gcp, from there follow the readme.

**Comment by codders** [comment]
Thanks for investigating and commenting!
