### ISSUE TITLE
flathunter  config help

### ISSUE THREAD

**Issue by Wolfsfrucht** [flathunters/flathunter#22]
Hello, 
how do you set the config?

If i set urls on line 13 i got errors

can one show his config? 
of course without his token

**Comment by codders** [comment]
Hi Wolfsfrucht,

My URLs look like this:

```
urls:
  - https://www.wg-gesucht.de/wohnungen-in-Berlin.8.2.1.0.html?offer_filter=1&city_id=8&noDeact=1&dFr=1591394400&dTo=1592344800&categories%5B%5D=2&rent_types%5B%5D=1&dFrDe=7&dToDe=7
```

Can you share what URLs you are using, and the full error message that you get?

Thanks,

Arthur

**Comment by Wolfsfrucht** [comment]
can I do, I will submit shortly

**Comment by Wolfsfrucht** [comment]
`martin@martin-Satellite-C660D:~/flathunter$ python3 flathunter.py
[2020/06/17 09:46:11|config.py         |INFO    ]: Using config /home/martin/flathunter/config.yaml
Traceback (most recent call last):
  File "flathunter.py", line 85, in <module>
    main()
  File "flathunter.py", line 62, in main
    config = Config(config_handle.name)
  File "/home/martin/flathunter/flathunter/config.py", line 24, in __init__
    self.config = yaml.safe_load(file)
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/martin/.local/lib/python3.8/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/home/martin/flathunter/config.yaml", line 15, column 1`

i hope it helps

**Comment by Wolfsfrucht** [comment]
for better view https://pastebin.com/WCBDWGaQ

**Comment by codders** [comment]
From the error message, it looks like you have a <TAB> character in your YAML file. Can you try replacing any <TAB> with <SPACE>? What does your `urls:` config look like?

**Comment by Wolfsfrucht** [comment]
I have in the urls only

`https://www.wg-gesucht.de/wohnungen-in-Koeln.73.2.1.0.html?offer_filter=1&city_id=73&noDeact=1&categories%5B%5D=2&rent_types%5B%5D=2&sMin=30&rMax=53`

**Comment by codders** [comment]
The URLs need to be a YAML list. That means they need to start with `<SPACE>-<SPACE><URL>`, like in the example I posted.

**Comment by Wolfsfrucht** [comment]
I will test it with your link, 
I will get back to you as soon as it works

**Comment by Wolfsfrucht** [comment]
same my config

https://pastebin.com/KjjjwW7D

**Comment by codders** [comment]
The first character on the line that includes your URL is a <TAB> character. It needs to be a <SPACE> character.

**Comment by Wolfsfrucht** [comment]
oh :D thanks didnt see it thanks for quick replay now it works :)
