### ISSUE TITLE
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

### ISSUE THREAD

**Issue by co-podo** [flathunters/flathunter#221]
```
(flathunter-xnX5VnTq) C:\Users\****\****\****\flathunter>python flathunt.py
[2022/09/16 19:35:34|config.py               |INFO    ]: Using config path C:\Users\****\****\****\flathunter/config.yaml
[2022/09/16 19:35:37|hunter.py               |INFO    ]: New offer: Kfz-Stellplatz, Aufzug,...HIER wird IHNEN vieles GEBOTEN
[2022/09/16 19:35:37|hunter.py               |INFO    ]: New offer: [TAUSCHWOHNUNG] Schöne Wohnung am BUGA Park
[2022/09/16 19:35:38|hunter.py               |INFO    ]: New offer: [TAUSCHWOHNUNG] Tausche 1 Raum Wohnung gegen Größeres
Traceback (most recent call last):
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\****\****\****\flathunter\flathunt.py", line 110, in <module>
    main()
  File "C:\Users\****\****\****\flathunter\flathunt.py", line 106, in main
    launch_flat_hunt(config, heartbeat)
  File "C:\Users\****\****\****\flathunter\flathunt.py", line 30, in launch_flat_hunt
    hunter.hunt_flats()
  File "C:\Users\****\****\****\flathunter\flathunter\hunter.py", line 54, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "C:\Users\****\****\****\flathunter\flathunter\sender_telegram.py", line 34, in process_expose
    self.__broadcast(
  File "C:\Users\****\****\****\flathunter\flathunter\sender_telegram.py", line 53, in __broadcast
    msg = self.__send_text(receiver, message)
  File "C:\Users\****\****\****\flathunter\flathunter\sender_telegram.py", line 84, in __send_text
    response = requests.request("POST", self.__text_message_url, data=payload)
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\****\.virtualenvs\flathunter-xnX5VnTq\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None))
```
fyi I did get the few notifications on telegram before it returned the error.

**Comment by codders** [comment]
This looks like it could be a temporary issue with the Telegram API. Do you still receive this? Is it reproducible?
