### ISSUE TITLE
HTTP Error 404 from urllib during WebDriver initialization

### ISSUE THREAD

**Issue by Weegee** [flathunters/flathunter#257]
Hello,

after pulling the latest changes from the repo the script crashes while trying to initialize the Chrome WebDriver for the crawler. I'm getting the following output:

```
[2022/11/09 19:08:18|config.py               |INFO    ]: Using config path /home/patrick/data/flathunter/config.yaml
[2022/11/09 19:08:18|chrome_wrapper.py       |INFO    ]: Initializing Chrome WebDriver for crawler...
Traceback (most recent call last):
  File "/home/patrick/data/flathunter/flathunt.py", line 109, in <module>
    main()
  File "/home/patrick/data/flathunter/flathunt.py", line 75, in main
    config.init_searchers()
  File "/home/patrick/data/flathunter/flathunter/config.py", line 87, in init_searchers
    CrawlImmobilienscout(self),
  File "/home/patrick/data/flathunter/flathunter/crawl_immobilienscout.py", line 40, in __init__
    self.driver = get_chrome_driver(driver_arguments)
  File "/home/patrick/data/flathunter/flathunter/chrome_wrapper.py", line 29, in get_chrome_driver
    driver = uc.Chrome(version_main=chrome_version, options=chrome_options) # pylint: disable=no-member
  File "/home/patrick/.local/share/virtualenvs/flathunter-4DLpNgap/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 240, in __init__
    patcher.auto()
  File "/home/patrick/.local/share/virtualenvs/flathunter-4DLpNgap/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 127, in auto
    release = self.fetch_release_number()
  File "/home/patrick/.local/share/virtualenvs/flathunter-4DLpNgap/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

The URLs I want flathunter to parse are:

```
urls:
     - https://www.immowelt.de/liste/hamburg-barmbek-nord/wohnungen/mieten?ami=60&d=true&efs=CERTIFICATE_OF_ELIGIBILITY&ffs=BALCONY_OR_TERRACE&lids=441375&lids=441509&pma=1000&rmi=2.5&sd=DESC&sf=TIMESTAMP&sp=1
     - https://www.immobilienscout24.de/Suche/de/hamburg/hamburg/hamburg-nord/wohnung-mit-balkon-mieten?haspromotion=false&numberofrooms=2.5-&price=-1000.0&livingspace=60.0-&exclusioncriteria=swapflat&pricetype=rentpermonth&geocodes=0200000006059,0200000006073,0200000006074&sorting=2
```

I've had the same issue on my server running on Python 3.9. I'll gladly provide more information if needed.

**Comment by codders** [comment]
What version of chrome do you have installed? Does this happen every time or just sometimes?

**Comment by Weegee** [comment]
I'm on Chromium (not Chrome, is that a problem?) 107 (107.0.5304.110). It happens every time I start the script.

**Comment by codders** [comment]
Looks like a problem with the version string parsing for chromium. I've made a PR #258 to address this - if the tests pass in a sec, I'll merge it and you can see if that fixes your issue

**Comment by Weegee** [comment]
Thanks for the quick response, unfortunately the issue persists:

```
[2022/11/10 08:17:31|config.py               |INFO    ]: Using config path /home/patrick/flathunter/config.yaml
[2022/11/10 08:17:31|logging.py              |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7f69614c8850>
[2022/11/10 08:17:31|chrome_wrapper.py       |INFO    ]: Initializing Chrome WebDriver for crawler...
Traceback (most recent call last):
  File "/home/patrick/flathunter/flathunt.py", line 109, in <module>
    main()
  File "/home/patrick/flathunter/flathunt.py", line 75, in main
    config.init_searchers()
  File "/home/patrick/flathunter/flathunter/config.py", line 87, in init_searchers
    CrawlImmobilienscout(self),
  File "/home/patrick/flathunter/flathunter/crawl_immobilienscout.py", line 40, in __init__
    self.driver = get_chrome_driver(driver_arguments)
  File "/home/patrick/flathunter/flathunter/chrome_wrapper.py", line 44, in get_chrome_driver
    driver = uc.Chrome(version_main=chrome_version, options=chrome_options) # pylint: disable=no-member
  File "/home/patrick/.local/share/virtualenvs/flathunter-8VR5ofyf/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 240, in __init__
    patcher.auto()
  File "/home/patrick/.local/share/virtualenvs/flathunter-8VR5ofyf/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 127, in auto
    release = self.fetch_release_number()
  File "/home/patrick/.local/share/virtualenvs/flathunter-8VR5ofyf/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by codders** [comment]
What do you get when you run `chromium --version` ?

**Comment by Weegee** [comment]
Output:
```
Chromium 107.0.5304.87 built on Debian 11.5, running on Debian 11.5
```

**Comment by codders** [comment]
Well, that's pretty mysterious. I get exactly the same here, and my flathunter runs okay.

If you run:
```
python -c "import sys; print(sys.platform)"
```

does it show 'linux'?

**Comment by codders** [comment]
Nice detective work :) I've created #259 which has a test specifically for your version string - that should work better. I'll merge it as soon as the tests pass.

**Comment by codders** [comment]
Can you pull the latest and try again? I hope that's working now

**Comment by Weegee** [comment]
It works now. Thank you! :)
