### ISSUE TITLE
python flathunt.py throws error

### ISSUE THREAD

**Issue by mayerniklas** [flathunters/flathunter#297]
Hi, 

I followed the instructions and configured the config file, however, I get the following ImportError when running ` python flathunt.py`

```
Traceback (most recent call last):
  File "/Users/nikmayer/Coding/flathunter/flathunt.py", line 13, in <module>
    from flathunter.hunter import Hunter
  File "/Users/nikmayer/Coding/flathunter/flathunter/hunter.py", line 7, in <module>
    from flathunter.config import YamlConfig
  File "/Users/nikmayer/Coding/flathunter/flathunter/config.py", line 12, in <module>
    from flathunter.crawl_ebaykleinanzeigen import CrawlEbayKleinanzeigen
  File "/Users/nikmayer/Coding/flathunter/flathunter/crawl_ebaykleinanzeigen.py", line 6, in <module>
    from flathunter.abstract_crawler import Crawler
  File "/Users/nikmayer/Coding/flathunter/flathunter/abstract_crawler.py", line 16, in <module>
    from flathunter import proxies
  File "/Users/nikmayer/Coding/flathunter/flathunter/proxies.py", line 3, in <module>
    from lxml.html import fromstring
  File "/Users/nikmayer/.local/share/virtualenvs/flathunter-BidRq-XA/lib/python3.10/site-packages/lxml/html/__init__.py", line 53, in <module>
    from .. import etree
ImportError: dlopen(/Users/nikmayer/.local/share/virtualenvs/flathunter-BidRq-XA/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_exsltDateXpathCtxtRegister'
```
Python version 3.10.9. 

Any idea how to fix this?

**Comment by codders** [comment]
This looks like a linker error. Do you have `libxml2-dev` (or whatever the Mac equivalent is) installed on your system? It seems like the python library `etree` is expecting some native support that is missing in your OS.

**Comment by codders** [comment]
Closing this for lack for feedback.
