### ISSUE TITLE
Problem with setup: need help

### ISSUE THREAD

**Issue by Louisbrau** [flathunters/flathunter#300]
Hello, I don't have real experience with code, but I tried to follow the instructions as good as I can. I already configured the config.yaml.dist, but I don't really understand where I have to copy it to. 

Now as I try to run the code, I get the following error:

PS C:\Users\Louis> pipenv run python flathunt.py
Traceback (most recent call last):
  File "C:\Users\Louis\flathunt.py", line 13, in <module>
    from flathunter.hunter import Hunter
  File "C:\Users\Louis\flathunter\hunter.py", line 7, in <module>
    from flathunter.config import YamlConfig
  File "C:\Users\Louis\flathunter\config.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Looking for help, thank you in advance!

**Comment by Louisbrau** [comment]
Update: I tried to install all packages individually, but now I get the following code: 

PS C:\Users\Louis> python flathunt.py
[2023/01/25 14:55:58|config.py               |INFO    ]: Using config path C:\Users\Louis/config.yaml
[2023/01/25 14:55:58|crawl_immobilienscout.py|ERROR   ]: Index error occurred
Traceback (most recent call last):
  File "C:\Users\Louis\flathunt.py", line 109, in <module>
    main()
  File "C:\Users\Louis\flathunt.py", line 105, in main
    launch_flat_hunt(config, heartbeat)
  File "C:\Users\Louis\flathunt.py", line 29, in launch_flat_hunt
    hunter.hunt_flats()
  File "C:\Users\Louis\flathunter\hunter.py", line 54, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\hunter.py", line 33, in crawl_for_exposes
    return chain(*[try_crawl(searcher, url, max_pages)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\hunter.py", line 33, in <listcomp>
    return chain(*[try_crawl(searcher, url, max_pages)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\hunter.py", line 25, in try_crawl
    return searcher.crawl(url, max_pages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\abstract_crawler.py", line 140, in crawl
    if re.search(self.URL_PATTERN, url):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by Louisbrau** [comment]
Not I'm here:

PS C:\Users\Louis> python flathunt.py
[2023/01/25 15:27:52|config.py               |INFO    ]: Using config path C:\Users\Louis/config.yaml
Traceback (most recent call last):
  File "C:\Users\Louis\flathunt.py", line 109, in <module>
    main()
  File "C:\Users\Louis\flathunt.py", line 105, in main
    launch_flat_hunt(config, heartbeat)
  File "C:\Users\Louis\flathunt.py", line 29, in launch_flat_hunt
    hunter.hunt_flats()
  File "C:\Users\Louis\flathunter\hunter.py", line 48, in hunt_flats
    .calculate_durations() \
     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\processor.py", line 40, in calculate_durations
    and self.config["google_maps_api"]["enable"]
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by codders** [comment]
If you're not using the google maps API, you can just remove those sections from your configuration file (`config.yaml`) and the error should go away.

**Comment by Louisbrau** [comment]
Thank. But now I get this:

PS C:\Users\Louis> python flathunt.py
[2023/01/25 15:45:03|config.py               |INFO    ]: Using config path C:\Users\Louis/config.yaml
[2023/01/25 15:45:03|crawl_immobilienscout.py|ERROR   ]: Index error occurred
Traceback (most recent call last):
  File "C:\Users\Louis\flathunt.py", line 109, in <module>
    main()
  File "C:\Users\Louis\flathunt.py", line 105, in main
    launch_flat_hunt(config, heartbeat)
  File "C:\Users\Louis\flathunt.py", line 29, in launch_flat_hunt
    hunter.hunt_flats()
  File "C:\Users\Louis\flathunter\hunter.py", line 54, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\hunter.py", line 33, in crawl_for_exposes
    return chain(*[try_crawl(searcher, url, max_pages)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\hunter.py", line 33, in <listcomp>
    return chain(*[try_crawl(searcher, url, max_pages)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\hunter.py", line 25, in try_crawl
    return searcher.crawl(url, max_pages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\abstract_crawler.py", line 140, in crawl
    if re.search(self.URL_PATTERN, url):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'


It seems like everytime i try to fix an error, a new one appears

**Comment by Louisbrau** [comment]
Hi Codder,
it work now! I got the first flats via telegram.

But I still get this error at the end:

File "C:\Users\Louis\flathunt.py", line 109, in <module>
    main()
  File "C:\Users\Louis\flathunt.py", line 105, in main
    launch_flat_hunt(config, heartbeat)
  File "C:\Users\Louis\flathunt.py", line 32, in launch_flat_hunt
    while config.loop_is_active():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\config.py", line 347, in loop_is_active
    return super().loop_is_active()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\config.py", line 179, in loop_is_active
    return self._read_yaml_path('loop.active', False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Louis\flathunter\config.py", line 134, in _read_yaml_path
    return config.get(parts[0], default_value)
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'




in the config it looks like this:
loop:
active: yes
sleeping_time: 700

**Comment by Louisbrau** [comment]
And at the top: crawl_immobilienscout.py|ERROR   ]: Index error occurred

I already added credits to recaptcha and filled in the api key
