### ISSUE TITLE
Problem with ChromeDriver - fails to start/aborts

### ISSUE THREAD

**Issue by 4symmetry19** [flathunters/flathunter#332]
Hi all, once again thanks for the amazing tool you built!
Starting a couple days ago, I started having problems running flathunter in Terminal on my Macbook (Mac OS 13.2.1). I would assume it is because of a background update of my Chrome browser? It is currently on version 110.0.5481.177 (but as said, it does background updates so I wouldn't have noticed an update). 

Here's the error message: 
`[2023/03/09 09:38:58|chrome_wrapper.py       |INFO    ]: Initializing Chrome WebDriver for crawler...
[2023/03/09 09:39:00|patcher.py              |INFO    ]: patching driver executable /Users/username/Library/Application Support/undetected_chromedriver/42fd038d95a0c502_chromedriver
Traceback (most recent call last):
  File "/Users/username/Documents/Python/Flathunter/flathunter-main/flathunt.py", line 118, in <module>
    main()
  File "/Users/username/Documents/Python/Flathunter/flathunter-main/flathunt.py", line 84, in main
    config.init_searchers()
  File "/Users/username/Documents/Python/Flathunter/flathunter-main/flathunter/config.py", line 100, in init_searchers
    CrawlImmobilienscout(self),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/Python/Flathunter/flathunter-main/flathunter/crawl_immobilienscout.py", line 40, in __init__
    self.driver = get_chrome_driver(driver_arguments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/Python/Flathunter/flathunter-main/flathunter/chrome_wrapper.py", line 44, in get_chrome_driver
    driver = uc.Chrome(version_main=chrome_version, options=chrome_options) # pylint: disable=no-member
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.local/share/virtualenvs/flathunter-main-5Sh0rgzD/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 431, in __init__
    super(Chrome, self).__init__(
  File "/Users/username/.local/share/virtualenvs/flathunter-main-5Sh0rgzD/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/Users/username/.local/share/virtualenvs/flathunter-main-5Sh0rgzD/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/Users/username/.local/share/virtualenvs/flathunter-main-5Sh0rgzD/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/username/.local/share/virtualenvs/flathunter-main-5Sh0rgzD/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 693, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/username/.local/share/virtualenvs/flathunter-main-5Sh0rgzD/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.local/share/virtualenvs/flathunter-main-5Sh0rgzD/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Users/username/.local/share/virtualenvs/flathunter-main-5Sh0rgzD/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:51163
from session not created: This version of ChromeDriver only supports Chrome version 111
Current browser version is 110.0.5481.177
Stacktrace:
0   42fd038d95a0c502_chromedriver       0x00000001008cb428 42fd038d95a0c502_chromedriver + 4899880
1   42fd038d95a0c502_chromedriver       0x0000000100848a23 42fd038d95a0c502_chromedriver + 4364835
2   42fd038d95a0c502_chromedriver       0x0000000100492bf6 42fd038d95a0c502_chromedriver + 474102
3   42fd038d95a0c502_chromedriver       0x00000001004c3970 42fd038d95a0c502_chromedriver + 674160
4   42fd038d95a0c502_chromedriver       0x00000001004ba3b8 42fd038d95a0c502_chromedriver + 635832
5   42fd038d95a0c502_chromedriver       0x0000000100506019 42fd038d95a0c502_chromedriver + 946201
6   42fd038d95a0c502_chromedriver       0x00000001005053af 42fd038d95a0c502_chromedriver + 943023
7   42fd038d95a0c502_chromedriver       0x00000001004fc333 42fd038d95a0c502_chromedriver + 906035
8   42fd038d95a0c502_chromedriver       0x00000001004c655f 42fd038d95a0c502_chromedriver + 685407
9   42fd038d95a0c502_chromedriver       0x00000001004c7a7e 42fd038d95a0c502_chromedriver + 690814
10  42fd038d95a0c502_chromedriver       0x000000010089879e 42fd038d95a0c502_chromedriver + 4691870
11  42fd038d95a0c502_chromedriver       0x000000010089d961 42fd038d95a0c502_chromedriver + 4712801
12  42fd038d95a0c502_chromedriver       0x00000001008a42ff 42fd038d95a0c502_chromedriver + 4739839
13  42fd038d95a0c502_chromedriver       0x000000010089e85a 42fd038d95a0c502_chromedriver + 4716634
14  42fd038d95a0c502_chromedriver       0x0000000100870fce 42fd038d95a0c502_chromedriver + 4530126
15  42fd038d95a0c502_chromedriver       0x00000001008be5c8 42fd038d95a0c502_chromedriver + 4847048
16  42fd038d95a0c502_chromedriver       0x00000001008be747 42fd038d95a0c502_chromedriver + 4847431
17  42fd038d95a0c502_chromedriver       0x00000001008d387f 42fd038d95a0c502_chromedriver + 4933759
18  libsystem_pthread.dylib             0x00007ff81cbfd259 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff81cbf8c7b thread_start + 15
`

Any help would be highly appreciated. :)

**Comment by codders** [comment]
Hi @4symmetry19 ,

This looks very similar to what we used to have with #213 (which is supposed to be resolved. We have code to detect the installed version of chrome and use that in the chrome-driver initialization: https://github.com/flathunters/flathunter/blob/main/flathunter/chrome_wrapper.py#L21-L34 .

Do you have Chromium and Chrome installed? What happens if you run `google-chome --version`, `chromium --version` and `chrome --version`?

**Comment by 4symmetry19** [comment]
For all the commands above, I get a version of:
`zsh: command not found: google-chrome`

I have Chrome, the web browser, installed as an app. What happens when I get that error is that a new Chrome window opens, then I get the error in terminal and the Chrome window closes again. 

But, alas, right after testing the commands above I just tried running flathunt.py again and now it magically works again. I would conclude that we do not know what is causing that error :D Chrome version is still  110.0.5481.177. 🤷🏻‍♀️

**Comment by codders** [comment]
Okay. I'm going to chalk this up to a caching issue with your system - sounds like it's going to be hard to reproduce. There is code in the project to try and auto-detect the currently installed version of `google-chrome`, but I've never tested it on a Mac and it might be that we need something different there for that platform. If you have tips about what the `google-chrome --version` equivalent is on your platform, we can adjust the version detection.
