### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by choeffer** [flathunters/flathunter#38]
Hello,

since one hour I am getting the following error message

```
[2020/07/09 15:42:01|config.py         |INFO    ]: Using config /home/choeffer/Dokumente/flathunter/config.yaml
Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "flathunt.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 21, in crawl_for_exposes
    return chain(*[searcher.crawl(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 21, in <listcomp>
    return chain(*[searcher.crawl(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/abstract_crawler.py", line 48, in crawl
    return self.get_results(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/abstract_crawler.py", line 39, in get_results
    entries = self.extract_data(soup)
  File "/home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py", line 81, in extract_data
    rooms = re.match(r'(\d+)', tags[1].text)[1]
TypeError: 'NoneType' object is not subscriptable
```

If you need more information for debugging the issue or additional logs, please let me know.

**Comment by choeffer** [comment]
```
[2020/07/09 15:52:26|config.py         |INFO    ]: Using config /home/choeffer/Dokumente/flathunter/config.yaml
> /home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py(82)extract_data()
-> rooms = re.match(r'(\d+)', tags[1].text)[1]
(Pdb) tags
[<span class="simpletag tag-small">41 m²</span>, <span class="simpletag tag-small">1 Zimmer</span>]
(Pdb) tags[1].text
'1 Zimmer'
(Pdb) continue
> /home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py(81)extract_data()
-> import pdb; pdb.set_trace()
(Pdb) tags[1].text
'70 m²'
(Pdb) continue
> /home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py(82)extract_data()
-> rooms = re.match(r'(\d+)', tags[1].text)[1]
(Pdb) continue
> /home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py(81)extract_data()
-> import pdb; pdb.set_trace()
(Pdb) tags[1].text
'35 m²'
(Pdb) continue
> /home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py(82)extract_data()
-> rooms = re.match(r'(\d+)', tags[1].text)[1]
(Pdb) tags[1].text
'2 Zimmer'
(Pdb) continue
> /home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py(81)extract_data()
-> import pdb; pdb.set_trace()
(Pdb) tags[1].text
'15 m²'
(Pdb) continue
> /home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py(82)extract_data()
-> rooms = re.match(r'(\d+)', tags[1].text)[1]
(Pdb) tags[1].text
'1 Zimmer'
(Pdb) continue
> /home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py(81)extract_data()
-> import pdb; pdb.set_trace()
(Pdb) tags[1].text
'Versand möglich'
(Pdb) continue
Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "flathunt.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 21, in crawl_for_exposes
    return chain(*[searcher.crawl(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/hunter.py", line 21, in <listcomp>
    return chain(*[searcher.crawl(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/abstract_crawler.py", line 48, in crawl
    return self.get_results(url, max_pages)
  File "/home/choeffer/Dokumente/flathunter/flathunter/abstract_crawler.py", line 39, in get_results
    entries = self.extract_data(soup)
  File "/home/choeffer/Dokumente/flathunter/flathunter/crawl_ebaykleinanzeigen.py", line 81, in extract_data
    import pdb; pdb.set_trace()
TypeError: 'NoneType' object is not subscriptable
```

**Comment by choeffer** [comment]
The funtion `re.match(r'(\d+)', tags[1].text)` in the line 81 in `crawl_ebaykleinanzeigen.py` seems to try to find a digit in a string which cannot be found in `Versand möglich`, but can be found in `1 Zimmer`.

But I do not undersand, why it is crashing and not executing the `except` path and continue. See snippet:

```
            try:
                self.__log__.debug(tags[1].text)
                import pdb; pdb.set_trace()
                rooms = re.match(r'(\d+)', tags[1].text)[1]
            except IndexError:
                self.__log__.debug("Keine Zimmeranzahl gegeben")
                rooms = "Nicht gegeben"
```

**Comment by choeffer** [comment]
#39 is a workaround for that issue. Its not a nice solution, but the error is logged and the programm can continue.

**Comment by choeffer** [comment]
can be closed, was already fixed by https://github.com/flathunters/flathunter/commit/735283a08294414b90b51a4d45d4b853daeafa4d

**Comment by codders** [comment]
Thanks for the report, and the pull request!
