### ISSUE TITLE
Immowelt crashes -  File "/flathunter/crawl_immowelt.py", line 87, in extract_data     address = address.find("span").text AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by miklyx** [flathunters/flathunter#414]
Immowelt parsing fells every time

`[2023/06/20 00:17:53|abstract_crawler.py     |DEBUG   ]: Got search URL https://www.immowelt.de/liste/berlin-friedrichshain/wohnungen/mieten?ami=50&d=true&pma=1000&r=2&sd=DESC&sf=TIMESTAMP&sp=1
Traceback (most recent call last):
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunt.py", line 109, in <module>
    main()
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunt.py", line 105, in main
    launch_flat_hunt(config, heartbeat)
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunt.py", line 29, in launch_flat_hunt
    hunter.hunt_flats()
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunter/hunter.py", line 54, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunter/hunter.py", line 33, in crawl_for_exposes
    return chain(*[try_crawl(searcher, url, max_pages)
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunter/hunter.py", line 33, in <listcomp>
    return chain(*[try_crawl(searcher, url, max_pages)
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunter/hunter.py", line 25, in try_crawl
    return searcher.crawl(url, max_pages)
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunter/abstract_crawler.py", line 142, in crawl
    return self.get_results(url, max_pages)
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunter/abstract_crawler.py", line 133, in get_results
    entries = self.extract_data(soup)
  File "/Users/mrashkovskiy/Documents/py/flathunt/flathunter/flathunter/crawl_immowelt.py", line 87, in extract_data
    address = address.find("span").text
AttributeError: 'NoneType' object has no attribute 'find'
`

**Comment by codders** [comment]
Hi @miklyx ,

I'm also seeing that here - I guess something on the Immowelt page has changed. I'll try and take a look today or latest tomorrow.

**Comment by jukoson** [comment]
I am not using flathunter, but discovered the same issue yesterday.
Not sure if Immowelt only recently added listings for wohnungsswap.de, but these listings do not have an address defined. That's why it the address parsing returns `None`. You could try and find the address or otherwise omit it if not available.

**Comment by codders** [comment]
Should be fixed on `main` - please pull the latest code and retest, and let me know here if we can close the issue.

**Comment by codders** [comment]
No complaints - marking this as closed. Please reopen if the issue reoccures.
