### ISSUE TITLE
ChromeNotFound running flathunt.py

### ISSUE THREAD

**Issue by Lamalord** [flathunters/flathunter#495]
After running the config wizard and then trying to run "python flathunt.py" I get the error ChromeNotFound:
python flathunt.py. I am using a Mac M1 machine.
          
[2023/10/10 21:25:58|config.py               |INFO    ]: Using config path /Users/user/Projects/flathunter/config.yaml
[2023/10/10 21:25:58|chrome_wrapper.py       |INFO    ]: Initializing Chrome WebDriver for crawler...
Traceback (most recent call last):
  File "/Users/user/Projects/flathunter/flathunt.py", line 99, in <module>
    main()
  File "/Users/user/Projects/flathunter/flathunt.py", line 95, in main
    launch_flat_hunt(config, heartbeat)
  File "/Users/user/Projects/flathunter/flathunt.py", line 35, in launch_flat_hunt
    hunter.hunt_flats()
  File "/Users/user/Projects/flathunter/flathunter/hunter.py", line 56, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/Users/user/Projects/flathunter/flathunter/hunter.py", line 35, in crawl_for_exposes
    return chain(*[try_crawl(searcher, url, max_pages)
  File "/Users/user/Projects/flathunter/flathunter/hunter.py", line 35, in <listcomp>
    return chain(*[try_crawl(searcher, url, max_pages)
  File "/Users/user/Projects/flathunter/flathunter/hunter.py", line 27, in try_crawl
    return searcher.crawl(url, max_pages)
  File "/Users/user/Projects/flathunter/flathunter/abstract_crawler.py", line 151, in crawl
    return self.get_results(url, max_pages)
  File "/Users/user/Projects/flathunter/flathunter/crawler/immobilienscout.py", line 90, in get_results
    soup = self.get_page(search_url, self.get_driver(), page_no)
  File "/Users/user/Projects/flathunter/flathunter/crawler/immobilienscout.py", line 65, in get_driver
    self.driver = get_chrome_driver(driver_arguments)
  File "/Users/user/Projects/flathunter/flathunter/chrome_wrapper.py", line 62, in get_chrome_driver
    chrome_version = get_chrome_version()
  File "/Users/user/Projects/flathunter/flathunter/chrome_wrapper.py", line 53, in get_chrome_version
    raise ChromeNotFound()
flathunter.exceptions.ChromeNotFound

**Comment by codders** [comment]
Probably going to sound like a dumb question, but do you have Google Chrome / Chromium installed?

**Comment by DawidNiezgodka** [comment]
Hi,
I'm having the same issue, and I have Google Chrome installed. Any idea how to fix the problem?
