### ISSUE TITLE
KeyError after 2captcha for immobilienscout24

### ISSUE THREAD

**Issue by arubacao** [flathunters/flathunter#67]
I'm happy to see that 2captcha was integrated into flathunters since immobilienscout24.de is triggering the captcha after 2x hits for a "selbst gezeichnetes Suchgebiet" link.
Unfortunately, I'm not able to get it completely up and running.
It seems like the captcha was successfully solved, it also shows up in the 2captcha statistics. 
This is the resulting log:

```
[2020/10/03 23:58:50|config.py         |INFO    ]: Using config /app/config.yaml
[2020/10/03 23:58:51|flathunt.py       |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7fdb050b43a0>
[2020/10/03 23:58:51|crawl_immobilienscout.py|DEBUG   ]: Got search URL https://www.immobilienscout24.de/Suche/shape/wohnung-mieten?shape=fWZ0ZEh3dGtlQXhWZWtAblJlQGBUdUFoaUB3Q0pvc0FtaUBjfUFtW19gQHNOakhvRmJBdUNqR3lKSXNFa0FxSHdKeWJAZXZBfVZ7cEB3akBpWnFCe29AbWJAfV1jUHxNZ1h4fkBtXW1iQG1iQHNWfU5vR2dLYnRAa01waUB0RGxxQG1HYHBAdEJmX0B7Q2p0QGtFbGtBfGVAYmpAblhlYEB6X0BkRnZlQWhQYF52ZkBmbkFqdEBoXHpE&numberofrooms=2.0-&price=-1300.0&livingspace=50.0-&sorting=2&enteredFrom=result_list&pagenumber={0}
[2020/10/03 23:58:53|abstract_crawler.py|DEBUG   ]: Google site key: <re.Match object; span=(49, 93), match='&k=6LeaILIZAAAAALTgLZV1AQXPc2dAsLItNYJ8jVvB&'>
[2020/10/03 23:58:58|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:03|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:08|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:13|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:19|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:24|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:29|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:34|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:39|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:44|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:49|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:54|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/03 23:59:54|abstract_crawler.py|DEBUG   ]: Captcha promise: OK|03AGdBq25VNbxPhhj-ezyN11xsib3B5QPdtKJo9ZUANoJCXhNG6e3juFSmFIrHvZYVXO_63cEOhOsl9vxmUDdwqfQKj858qVkI-zSoT7idq99rB6uoV0z9WsX4D4TeQdjwlFozEIrIgZ5u12XcAUIfGAGSDrkA3xgdUtwWOuk8swEiW7u51Y_sf4r3GMX0UMgX0KksNv238L9eM26fEa3hDPMr0raK6vpsFUOPW0NxH-vjYTQ4ZDp_LL-8auv9FGn4bfkQTzNpDE71Nn-CGw5iVyEZc_mRupXhrHwD9FENIOokXeB1Iwm6v1pccKEvsrnsoJ5rmkBP5wr2YXDvld8p7VufhtwAk8GUaipG0kEiwpBEOrFKQc1L7t-qp4gZcITfQvjyqOlxEdo8tPTfIt4tIVcZrlGvGOql0qeR57d_X8w5oISKzsMSP6glD3RMy6GeSNVzWpaqfq861qOiDy9nqeQhWyRmBrhJtDGbqBOMQ1EtWKnPQ3mjU98
[2020/10/03 23:59:58|crawl_immobilienscout.py|DEBUG   ]: [123231487, 123210362, 123202495, 123201463, 48470193, 123184168, 123145073, 123020022, 123083698, 123063242, 123054184, 123041195, 123030893, 122974183, 122960443, 122923251, 122915078, 119193192, 122543400, 122810740]
Traceback (most recent call last):
  File "/app/flathunter/crawl_immobilienscout.py", line 134, in extract_data
    image = image_tag["src"]
  File "/usr/local/lib/python3.8/site-packages/bs4/element.py", line 992, in __getitem__
    return self.attrs[key]
KeyError: 'src'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "flathunt.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()
  File "/app/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/app/flathunter/hunter.py", line 21, in crawl_for_exposes
    return chain(*[searcher.crawl(url, max_pages)
  File "/app/flathunter/hunter.py", line 21, in <listcomp>
    return chain(*[searcher.crawl(url, max_pages)
  File "/app/flathunter/abstract_crawler.py", line 121, in crawl
    return self.get_results(url, max_pages)
  File "/app/flathunter/crawl_immobilienscout.py", line 64, in get_results
    entries = self.extract_data(soup)
  File "/app/flathunter/crawl_immobilienscout.py", line 136, in extract_data
    image = image_tag["data-lazy-src"]
  File "/usr/local/lib/python3.8/site-packages/bs4/element.py", line 992, in __getitem__
    return self.attrs[key]
KeyError: 'data-lazy-src'
```

Great repo btw! Thx for the good work!

**Comment by codders** [comment]
Hi @arubacao ,

Thanks for the report. I had a go at fixing that with PR #68 . Please try fetching the latest code from the `main` branch and let me know if you have any luck.

**Comment by arubacao** [comment]
Thx @codders for the quick response.

I'm now getting a new error:

```
[2020/10/04 12:07:11|config.py         |INFO    ]: Using config /app/config.yaml
[2020/10/04 12:07:13|flathunt.py       |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7f6bfdb2f3a0>
[2020/10/04 12:07:13|crawl_immobilienscout.py|DEBUG   ]: Got search URL https://www.immobilienscout24.de/Suche/shape/wohnung-mieten?shape=fWZ0ZEh3dGtlQXhWZWtAblJlQGBUdUFoaUB3Q0pvc0FtaUBjfUFtW19gQHNOakhvRmJBdUNqR3lKSXNFa0FxSHdKeWJAZXZBfVZ7cEB3akBpWnFCe29AbWJAfV1jUHxNZ1h4fkBtXW1iQG1iQHNWfU5vR2dLYnRAa01waUB0RGxxQG1HYHBAdEJmX0B7Q2p0QGtFbGtBfGVAYmpAblhlYEB6X0BkRnZlQWhQYF52ZkBmbkFqdEBoXHpE&numberofrooms=2.0-&price=-1300.0&livingspace=50.0-&sorting=2&enteredFrom=result_list&pagenumber={0}
Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "flathunt.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()
  File "/app/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/app/flathunter/hunter.py", line 21, in crawl_for_exposes
    return chain(*[searcher.crawl(url, max_pages)
  File "/app/flathunter/hunter.py", line 21, in <listcomp>
    return chain(*[searcher.crawl(url, max_pages)
  File "/app/flathunter/abstract_crawler.py", line 121, in crawl
    return self.get_results(url, max_pages)
  File "/app/flathunter/crawl_immobilienscout.py", line 58, in get_results
    return self.get_entries_from_javascript()
  File "/app/flathunter/crawl_immobilienscout.py", line 87, in get_entries_from_javascript
    result_json = self.driver.execute_script('return IS24.resultList;')
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: IS24 is not defined
  (Session info: headless chrome=85.0.4183.121)
```

I also tried it without headless mode on my local pc and it seems to fail before actually opening the page.
![Anmerkung 2020-10-04 140822](https://user-images.githubusercontent.com/7462542/95015074-45e6ce80-064b-11eb-8943-df68d0dc3eaa.jpg)

**Comment by codders** [comment]
What's the URL you are using? What does your config look like?

**Comment by arubacao** [comment]
All relevant config settings:
```
---
verbose: true

loop:
    active: no
    sleeping_time: 600

database_location: /app/database

urls:
  - https://www.immobilienscout24.de/Suche/shape/wohnung-mieten?shape=fWZ0ZEh3dGtlQXhWZWtAblJlQGBUdUFoaUB3Q0pvc0FtaUBjfUFtW19gQHNOakhvRmJBdUNqR3lKSXNFa0FxSHdKeWJAZXZBfVZ7cEB3akBpWnFCe29AbWJAfV1jUHxNZ1h4fkBtXW1iQG1iQHNWfU5vR2dLYnRAa01waUB0RGxxQG1HYHBAdEJmX0B7Q2p0QGtFbGtBfGVAYmpAblhlYEB6X0BkRnZlQWhQYF52ZkBmbkFqdEBoXHpE&numberofrooms=2.0-&price=-1300.0&livingspace=50.0-&sorting=2&enteredFrom=result_list

filters:
  - "zwischenmiete"
  - "befristet"

captcha:
  api_key: xxx
  driver_path: /usr/bin/chromedriver
  driver_arguments:
    - "--headless"
    - "--no-sandbox"
    - "--disable-gpu"
    - "window-size=1920,1080"

telegram:
    bot_token: xxx
    receiver_ids:
      - xxxx
```

**Comment by arubacao** [comment]
Same error occurs for a "normal" immoscout24 link
`https://www.immobilienscout24.de/Suche/de/bayern/muenchen/maxvorstadt/wohnung-mieten?sorting=2`

**Comment by codders** [comment]
Okay. I tried something else now. Can you fetch the latest and let me know what happens?

**Comment by arubacao** [comment]
Nope. But I think I fixed the problem for me. I'll send a PR

```
[2020/10/04 16:46:06|config.py         |INFO    ]: Using config /app/config.yaml
[2020/10/04 16:46:07|flathunt.py       |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7ffad26d57f0>
[2020/10/04 16:46:07|crawl_immobilienscout.py|DEBUG   ]: Got search URL https://www.immobilienscout24.de/Suche/de/bayern/muenchen/maxvorstadt/wohnung-mieten?sorting=2&pagenumber={0}
[2020/10/04 16:46:08|crawl_immobilienscout.py|WARNING ]: Unable to find IS24 variable in window
```

**Comment by codders** [comment]
Thanks for that. I've merged it in. It's great if that's working for you. I'm a bit suspicious because I see this sometimes working and sometimes not - 'window.IS24' and 'IS24' should be the same. But let's see what experience other users have.

**Comment by arubacao** [comment]
I also don't know why IS24 didn't work here since it's clearly working in a normal browser console :D 
Maybe checking for both could be an option then? 
nevertheless, I'm going to close it for now. Thanks!
